---
name: Haargos
description: |
  Monitoring and advanced analytics, alerts, and support.
  Stay informed about your smart home's health and performance.
version: 1.5.0
slug: haargos
init: false
boot: auto
startup: services
apparmor: true
url: "https://haargos.com"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  agent_token: ""
  ha_access_token: ""
  debug_mode: false
  dev: false
schema:
  agent_token: password
  ha_access_token: "str?"
  debug_mode: bool
  dev: bool
map:
  - "config"

codenotary: codenotary@haargos.com
hassio_api: true
homeassistant_api: true
docker_api: false
devices:
  - "/var/run/docker.sock:/var/run/docker.sock"

image: haargos/{arch}
